id: 7ead63963bad46178496eb29fa9c85f7
title: Toh_325-The_Verses_of_Naga_King_Drum-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-025
  eft-text-version: 1.1.2 2020
